data:
  build: ./data
  volumes:
    - /var/lib/mysql
    - /var/www/ghost/content
#    - /Users/mewm/www/ghost-theme:/var/www/ghost/content/themes/casper This can be added for theme development. Comment out the theme stuff in run-ghost.sh before rebuilding
db:
  build: ./mariadb
  ports:
    - "3305:3305"
  volumes_from:
    - data
  environment:
    - DEFAULT_USER=foobar # A user with this name will be created
    - DEFAULT_PASS=foobarz
    - PORT=3305
web:
  build: ./ghost
  ports:
    - "2368:2368"
  links:
    - db:database
  volumes_from:
    - data
  environment:
    - DB_HOST=database
    - DB_CLIENT=mysql
    - DB_USER=foobar
    - DB_PASSWORD=foobarz
    - DB_PORT=3305
    - DB_DATABASE=ghost
    - NODE_ENV=production
    - URL=http://tiago.griffo.me
    - THEME_SOURCE=https://github.com/tgriffo/ghost-theme # Git repo to fetch theme from
    - NEW_RELIC_LICENSE_KEY=e68f1e2325c9fe241763a5d8d5c83f52c709430b
#newrelicservermon:
#  image: uzyexe/newrelic
#  hostname: tiago.griffo.me
#  environment:
#    - NEW_RELIC_LICENSE_KEY=e68f1e2325c9fe241763a5d8d5c83f52c709430b